name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Root Package Script
      run: ./test_root_package.sh
    - name: Run Virtual Workspace Script
      run: ./test_virtual_workspace.sh
